### ISSUE TITLE
Map missing features

### ISSUE THREAD

**Issue by BlitzBanana** [nutshell-lab/meilisearch-ex#10]
See https://github.com/nutshell-lab/meilisearch-ex/issues/6#issuecomment-1581417824.
[Integration guide](https://github.com/meilisearch/integration-guides/blob/main/resources/README.md)

There are some missing features regarding latest Meilisearch releases.
We should document them in the README.md.

Here are the ones I can recall:
- Search using GET http method
- [Get documents by filter](https://github.com/nutshell-lab/meilisearch-ex/issues/8)
- [Delete documents by filter](https://github.com/nutshell-lab/meilisearch-ex/issues/9)

**Comment by brunoocasali** [comment]
I think we can close this one @BlitzBanana :)

There is no need to support GET HTTP calls for search since this is only used in the front end for a specific reason. 
Also I'm going to create the other issues ASAP!
