### ISSUE TITLE
Repository compliance to Meilisearch integration standards

### ISSUE THREAD

**Issue by BlitzBanana** [nutshell-lab/meilisearch-ex#6]
See https://github.com/nutshell-lab/meilisearch-ex/issues/2#issuecomment-1559929761

@brunoocasali tell me if you need mee to update something on the repo metadata.

**Comment by brunoocasali** [comment]
Here are the guidelines to put this integration into the standards of Meilisearch: https://github.com/meilisearch/integration-guides/blob/main/resources/build-integration.md

- [ ] Docker/Docker-compose
- [ ] Improve the usage samples of the README
- [ ] Map missing features
